language: node_js
os: linux
strategy: git

node_js:
  - "stable"

cache: npm

script: 
  # - npm test
  - npm run production
deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master