language: node_js
node_js:
  - "stable"

cache: npm
script: 
  # - npm test
  - npm run deploy
deploy:
  provider: pages
  keep_history: true
  skip_cleanup: true
  edge: true
  github_token: $GITHUB_TOKEN 
  on:
    branch: gh-pages
# Set in the settings page of your repository, as a secure variable