language: node_js
node_js:
  - "stable"

cache: npm
script: 
  # - npm test
  - npm run deploy
deploy:
  provider: pages
  local_dir: build
  cleanup: true
github_token: TRV_GIT_TOKEN  
# Set in the settings page of your repository, as a secure variable