language: node_js
node_js:
  - "stable"

cache: npm
script: 
  # - npm test
  - npm run deploy
deploy:
  provider: pages
  keep_history: true
  edge: true
  cleanup: false
  github_token: $GITHUB_TOKEN 
  # Set in the settings page of your repository, as a secure variable